check now counts and diplays the number of attached volumes in the output

diff --git a/check_aws_snapshots b/check_aws_snapshots
--- a/check_aws_snapshots
+++ b/check_aws_snapshots
@@ -6,15 +6,24 @@ if [[ $# -ne 2 ]] || ! [[ -e $1 ]]; then
         exit
 fi
 
+
+  volumes=0
+
+for zones in $(cat tmp_zones);
+do
+  volumes=$(($num+$(cat "$1" | grep "$(tail -n1 "$1" | awk '{print $1}')" | grep "$zones" | grep "Mounted Volumes" | awk '{print $5}')))
+done
+
+
+
+
 for x in CRITICAL WARNING OK ; do
+num="$(cat "$1" | grep $(tail -n1 "$1" | awk '{print $1}') | grep "$x" | wc -l )"
+  if [[  "$num" -gt 0 ]]; then
 
-numerrors="$(cat "$1" | grep $(tail -n1 "$1" | awk '{print $1}') | grep "$x" | wc -l )"
-
-  if [[  "$numerrors" -gt 0 ]]; then
-
-    if [[ $x = "CRITICAL" ]]; then "echo $x - $numerrors critical errors have occured, please check the logs" exit "2"
-    elif [[ $x = "WARNING" ]]; then echo "WARNING - $numerrors volumes have fewer than "$2" snapshots"; exit "1"
-    elif [[ $x = "OK" ]]; then echo "OK - $numerrors snapshots taken"; exit "0"
+    if [[ $x = "CRITICAL" ]]; then echo "$x - $num critical errors have occured, please check the logs"; exit 2
+    elif [[ $x = "WARNING" ]]; then echo "$x - $num of $volumes volumes have fewer than "$2" snapshots"; exit 1
+    elif [[ $x = "OK" ]]; then echo "$x - $num snapshots taken of $volumes attached volumes"; exit 0
     fi
   fi
   
